### ISSUE TITLE
chats list for the current user

### ISSUE THREAD

**Issue by almaz-uno** [optriment/optrispace-backend#112]
Add endpoint `GET /chats`. It must return all chats for the current user (where she/he is a participant). List should be sorted against last message posted in chat.

Backend should return array of objects:

- id - chat-id
- topic
- kind (application, contract)
- title (job title or contract title depends on kind)
- job_id, if applicable
- application_id, if applicable
- contract_id, if applicable
- paricipants[]
- - id
- - display_name
- - ethereum_address

**Comment by gruz0** [comment]
👍
