### ISSUE TITLE
Add column `visibility` to `jobs` table

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-backend#139]
We pay for this job in crypto:
https://my.optrispace.com/jobs/ULKtiVBowV7aBfQkwXaE7g/
---

Hi guys!

We would like to let customers to create hidden jobs on our platform. It can be useful to share a specific job with somebody, but don't return this job in jobs list.

In this task you need to add a new column to `jobs` table, filter by this field in SQL query and then add tests to cover this case.

## Acceptance Criteria

Hidden jobs are excluded from `GET /jobs` endpoint

## Recommended steps

First of all, please take a look at our [CONTRIBUTING.md](https://github.com/optriment/optrispace-backend/blob/develop/CONTRIBUTING.md).

Make sure you have running PostgreSQL instance on your computer:

```bash
cd ./ops/docker-compose-dev
docker compose up postgres
```

### Add a new column to `jobs` table

Create a new migration to add `visibility` (or suggest your own naming) column to `jobs` table (`index`, `default: 'public'`). I think it would be good to have these values: `public`, `hidden`. In the future we may want to extend it by adding `private` value, but now we need only two of them.

To do this execute in your terminal following command to create two new migrations:

```bash
make migrate-new-script SCRIPT_TITLE=add-visibility-to-jobs
```

Take a look into `./pkg/db/db-migrations/scripts` directory.

There will be two new files (one for `up` and one for `down` migrations).
Add required SQL queries to each of them (`ALTER` and `DROP`).

And then apply migrations:

```bash
make migrate-up
```

### Add additional condition to SQL query that returns a list of jobs

Add condition to `./pkg/db/sqlc/queries/jobs.sql` into `JobsList` query to filter by `public` `visibility`

In the project root generate sqlc files:

```bash
make sqlc
```

At this moment you can add tests.

### Add tests

Tests for jobs are located at `./intest/job_test.go`.

You need to add more tests to section `TestGetJobs`.

Take a look to [Running Tests](https://github.com/optriment/optrispace-backend/blob/develop/CONTRIBUTING.md#running-tests) section in CONTRIBUTING.md.

## Feel free to ask any questions to solve this task

Please ask me anything whatever you need to make this task done 🙏

**Comment by rafiramadhana** [comment]
can I help with this?

**Comment by gruz0** [comment]
> can I help with this?

Of course! It would be great!
Do you need any help from me?

**Comment by rafiramadhana** [comment]
i think the requirement is quite clear for now

**Comment by rafiramadhana** [comment]
but maybe i want to ask for your opinion @gruz0

the existing interface for `JobList` is:

```go
func (q *Queries) JobsList(ctx context.Context) ([]JobsListRow, error) {
```

for the new one, where we can filter by _visibility_, would you prefer:

(1) having a `string` of visibility:

```go
func (q *Queries) JobsList(ctx context.Context, visibility string) ([]JobsListRow, error) {
```

(2) or having a `struct` of filter:

```go
type JobListFilter struct {
    Visibility string
}

func (q *Queries) JobsList(ctx context.Context, filter JobListFilter) ([]JobsListRow, error) {
```

i prefer the (2), because it will be easier for us to add another filter in the future. We don't need to update existing unit tests when adding a new filter later on.

or do you have other preferences?

**Comment by gruz0** [comment]
> i prefer the (2), because it will be easier for us to add another filter in the future.

Agree 100%, @neverbeenthisweeb.

**Comment by rafiramadhana** [comment]
ok will proceed with that

**Comment by rafiramadhana** [comment]
@gruz0 hi one question

do you know how to _force_ sqlc to generate a struct arg for us?

each time i do `make sqlc`, i always ended up with a `, visibility string`:

```sql
-- name: JobsList :many
select
     j.id
    ,j.title
    ,j.description
    ,j.budget
    ,j.duration
    ,j.created_at
    ,j.created_by
    ,j.updated_at
    ,(select count(*) from applications a where a.job_id = j.id) as application_count
    ,(CASE WHEN p.display_name = '' THEN p.login ELSE p.display_name END)::varchar AS customer_display_name
    ,p.ethereum_address AS customer_ethereum_address
    ,j.visibility
    from jobs j
    join persons p on p.id = j.created_by
    where j.blocked_at is null and j.suspended_at is null and j.visibility = @visibility::varchar
    order by j.updated_at desc;
```

```go
func (q *Queries) JobsList(ctx context.Context, visibility string) ([]JobsListRow, error) {
```

i still can't force sqlc to generate us:

```go
func (q *Queries) JobsList(ctx context.Context, arg JobsListParams) ([]JobsListRow, error) {
```

any advice? or help? thank you

i've tried reading https://docs.sqlc.dev/en/stable/howto/named_parameters.html but still clueless about this

:cry:

**Comment by gruz0** [comment]
Can you push temporary commit or attach the diff?
Just to reproduce this behaviour on my side.

**Comment by gruz0** [comment]
Hmm... I think you can use `and j.visibility = 'public'` for now in SQL statement, just not to spend extra time to solve "future features" which will may not come. In the `JobsList` we don't need any filters at the moment, so don't need to add it right now.

If we will need them in the future – we will add it later :-)

I have another issue in my backlog to add filters on frontend and then implement in on backend. When we decide which filters will we use – we can get back into this SQL query with named parameters and refactor it.

WDYT?

**Comment by rafiramadhana** [comment]
> Hmm... I think you can use and j.visibility = 'public' for now in SQL statement, just not to spend extra time to solve "future features" which will may not come. In the JobsList we don't need any filters at the moment, so don't need to add it right now.

@gruz0 i see. LGTM, we can proceed by having `j.visibility = 'public'` in the query and no changes on `JobList` parameters.
