### ISSUE TITLE
Returns `jobs` ordered descending by `updated_at` instead of `created_at`

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-backend#141]
https://my.optrispace.com/jobs/2ZPoxJXuYnZZ3KQ3VBmzsA/
---

We would like to change ordering while returning list of jobs (`GET /jobs`).

Who can help us with this task?

Files to change:
1. https://github.com/optriment/optrispace-backend/blob/develop/pkg/db/sqlc/queries/jobs.sql#L1
2. https://github.com/optriment/optrispace-backend/blob/develop/Makefile#L16
3. https://github.com/optriment/optrispace-backend/blob/develop/intest/job_test.go#L398

**Comment by rafiramadhana** [comment]
Hi, i can help with this.
